# 内存数据库和 JPA 的配置.
spring:
#  profiles:
#    active: pg
  datasource:
    url: jdbc:hsqldb:mem:dbtest
    username: root
    password: 123456
    driver-class-name: org.hsqldb.jdbcDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: hsqldb
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql

# 日志级别
logging:
  file:
    name: logs/fenix-example.log
  level:
    root: info

# Fenix 的几个配置，都有默认值. 所以通常不需要配置，下面的配置代码也都可以删掉，你视具体情况配置即可.
fenix:
  debug: false
  print-banner: true
  print-sql:
  xml-locations:
    - fenix
    - myfenix
  handler-locations: com.blinkfox.fenix.example.handler
  predicate-handlers:
  underscore-transformer-prefix:
