# PostgreSQL 数据库的配置.
spring:
  datasource:
    url: jdbc:postgresql://172.25.2.9:6543/db_tcs
    username: sa
    password: 123456
    driver-class-name: org.postgresql.Driver
    platform: postgres
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
