# 内存数据库和 JPA 的配置.
spring:
  datasource:
    url: jdbc:hsqldb:mem:dbtest
    username: test
    password: 123456
    driver-class-name: org.hsqldb.jdbcDriver
    platform: hsqldb
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

# 日志级别
logging:
  file:
    name: logs/fenix-example.log
  level:
    root: info

# Fenix 的几个配置，都有默认值. 所以通常不需要配置，下面的配置代码也都可以删掉，你视具体情况配置即可.
fenix:
  print-banner: true
  print-sql:
  xml-locations:
    - fenix
    - myfenix
  handler-locations: com.blinkfox.fenix.example.handler
  predicate-handlers:
