# PostgreSQL 数据库的配置.
spring:
  datasource:
    url: jdbc:postgresql://172.125.12.19:6543/db_tcs
    username: sa
    password: 123456
    driver-class-name: org.postgresql.Driver
    platform: postgres
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    # 以下配置用于提高批量操作的相关性能.
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 500
          batch_versioned_data: true
